import './globals.css'
import { Inter } from 'next/font/google'
import { NavBar } from '@/components/section/navbar'
import { Footer } from '@/components/section/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Din Mart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
          {children}
        <Footer />
      </body>
    </html>
  )
}
