const Pages = ({ params, searchParams }: {
    params: { pagename: string },
    searchParams: { id: string },
  }) => {


    return (
        <div className="mx-32 my-16 flex flex-col gap-16 justify-between justify-items-center mt-24">
            <h1 className="text-left text-lg tracking-widest font-bold uppercase">{params.pagename.replaceAll('-', ' ')}</h1>
            <p className="mt-5 tracking-wider">Lorem ipsum dolor sit amet. Et quisquam commodi aut tempore alias At dicta voluptates non asperiores facere. Hic dolores nisi non quia quod sed excepturi pariatur ex voluptate aperiam cum amet possimus eum quos facere! Et quos adipisci non tempore dolores eos sunt cupiditate in consequatur doloremque quo perspiciatis earum. 33 pariatur recusandae et maiores modi ut numquam consequatur non facere impedit hic placeat impedit. Eum error dolorum eum dolorem dignissimos ut voluptatem fugiat ut eius omnis. Cum facilis eius et sunt ullam ea quos porro eum corrupti incidunt nam nesciunt amet nam velit dolores id eveniet amet. Et ducimus delectus aut dolor officia 33 eligendi blanditiis sed quia porro sed nihil provident in odio unde ut consequuntur iusto. Sed galisum doloribus id culpa magni aut sint quod et magni nihil qui odit ullam. Ad blanditiis repellat eum praesentium galisum qui impedit nostrum eum architecto beatae et assumenda consequatur. </p><p>Et architecto recusandae quo temporibus dicta sed consequatur animi et harum consequatur. Non tempora tempore in nihil explicabo vel quae itaque et voluptatem cupiditate sit culpa animi. Aut internos delectus vel commodi fuga sed architecto consequuntur et iure suscipit cum inventore voluptas sed libero praesentium et enim eaque. In voluptas totam non rerum soluta et placeat assumenda. Et earum internos ab necessitatibus consequatur et repudiandae quam aut illum dolor et illo sunt. Id excepturi magni ea quia dolores ab beatae nemo est minima suscipit aut sequi numquam qui inventore eveniet. Est molestiae nobis in dignissimos eaque et omnis placeat aut dolores veniam et quos sapiente ea velit adipisci et quod tempora. </p><p>Aut enim beatae eos odit architecto sit dolores numquam. Et repudiandae consequatur et ipsum blanditiis non sapiente aspernatur ex galisum consequatur. Et impedit dolorem est voluptatem rerum et officiis dolores sed voluptate enim ut dolorem numquam. Aut cupiditate nihil aut consequatur maiores At nobis doloremque aut quia quaerat est provident beatae et possimus eligendi eos ipsa aliquid. Eos consequatur sint quo aperiam nobis rem adipisci voluptatum sed voluptas iure! 33 nobis recusandae At natus blanditiis et recusandae nostrum. Et molestiae voluptas At harum dolorum ut labore ratione. Quo amet omnis ut sunt corporis eos quia molestiae et voluptas culpa. Aut vero beatae rem ipsa necessitatibus et voluptatem molestiae ab officiis deserunt sed obcaecati rerum? </p>
        </div>
    )
}

export default Pages;